# Sources:
# https://github.com/replicatedhq/outdated/blob/v0.3.3/deploy/.goreleaser.yaml
project_name: kubectl-bd-xray
release:
  github:
    owner: blackducksoftware
    name: kubectl-bd-xray
builds:
  - id: bd-xray
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
    env:
      - CGO_ENABLED=0
    main: cmd/bd-xray/main.go
    ldflags: -s -w
      -X github.com/blackducksoftware/kubectl-bd-xray/pkg/version.version={{.Version}}
      -X github.com/blackducksoftware/kubectl-bd-xray/pkg/version.gitSHA={{.Commit}}
      -X github.com/blackducksoftware/kubectl-bd-xray/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: bd-xray
    hooks: {}
archives:
  - id: bd-xray
    builds:
      - bd-xray
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}-{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
    name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
